### ISSUE TITLE
Duplicate entry_id

### ISSUE THREAD

**Issue by jaylevitt** [seattlerb/rdoc_osx_dictionary#5]
OS X 10.6.8, ruby 1.9.2-p290, XCode 3.2.6, rubygems 1.8.2, blank gemset with:
- rdoc_osx_dictionary 2.0.0
- rails 3.1.3
- and their dependencies

I get:

```
BCDEFGHIJKLMNOPRSTU! YAY!! All done!!!
/Developer/Extras/Dictionary Development Kit/bin/build_dict.sh: line 55: [: =0: integer expression expected
/Developer/Extras/Dictionary Development Kit/bin/build_dict.sh: line 61: [: =0: integer expression expected
- Building RubyAndGems.dictionary.
- Cleaning objects directory.
- Preparing dictionary template.
/Developer/Extras/Dictionary Development Kit/bin/generate_dict_template.sh: line 25: [: =0: integer expression expected
/Developer/Extras/Dictionary Development Kit/bin/generate_dict_template.sh: line 28: [: =0: integer expression expected
- Preprocessing dictionary sources.
- Extracting index data.
- Preparing dictionary bundle.
- Adding body data.
- Preparing index data.
*** Duplicate entry_id: [defs,AbstractController,,DoubleRenderError,new] at /Developer/Extras/Dictionary Development Kit/bin/replace_entryid_bodyid.pl line 88, <ENTRY_TO_BODY> line 126.
Error.
command failed
```

Do I need a newer XCode now?

**Comment by zenspider** [comment]
Newer xcode? no. 

This is probably because rails sucks. Simple as that. I need to do some more guards against their bullshit. :(

I'll test against rails 3.1.3.

**Comment by zenspider** [comment]
Hrm... I just did:

```
rm -rf ~/.ri
gem i -i xxx rails -v 3.1.3 --no-rdoc --no-ri
GEM_HOME=xxx GEM_PATH=tmp/isolate/ruby-1.8 ruby -Ilib bin/rdoc_osx_dictionary 
```

and it worked fine.... so... maybe you do need a newer xcode? What do you have?

**Comment by jaylevitt** [comment]
I'm on XCode 3.2.6. You?

**Comment by zenspider** [comment]
On Dec 17, 2011, at 15:29 , Jay Levitt wrote:

> I'm on XCode 3.2.6. You?

4.2

So... MAYBE that's it... but I doubt it's changed (much) since then. A duplicate ID _should_ be based on what I feed it, not how it treats it.

**Comment by jaylevitt** [comment]
Content preview:  Hm.. Well, I'm happy to try stuff, debug, give you SSH access,
    etc. I'd love to get this working again. Let me know! [...] 

 Content analysis details:   (-1.9 points, 5.0 required)

  pts rule name              description

---

 -0.0 T_RP_MATCHES_RCVD      Envelope sender domain matches handover relay
                             domain
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]
  0.0 MIME_QP_LONG_LINE      RAW: Quoted-printable line longer than 76 chars

Hm.. Well, I'm happy to try stuff, debug, give you SSH access, etc.  I'd love to get this working again. Let me know!

**Comment by ascarter** [comment]
I'm seeing:

**\* Duplicate entry_id: [defs,Exception2MessageMapper,Fail] at /Developer/Extras/Dictionary Development Kit/bin/replace_entryid_bodyid.pl line 88, <ENTRY_TO_BODY> line 2163.
Error.

Using Xcode 4.2.1, rbenv Ruby 1.9.3-p0, no rails installed in this rbenv.

**Comment by zenspider** [comment]
OK. I have a repro on 1.9.3 only. Odd.

**Comment by zenspider** [comment]
Fixed
