### ISSUE TITLE
Doesn't seem to work on Yosemite 

### ISSUE THREAD

**Issue by atmosx** [seattlerb/rdoc_osx_dictionary#8]
Hello,

Tried to install multiple times the gem. The first time I run the binary came up with an error which I can't reproduce. Then removed and re-installed multiple times.

I tried using both 'rvm' and standard ruby (osx pre-installed binary) but I can't see anything ruby-related in my 'Dictionary' application. Run `rdoc_osx_dictionary` in the terminal but nothing seems to happen.

Ty

**Comment by zenspider** [comment]
@zalt50 any ideas?

**Comment by zalt50** [comment]
Mmm...it still works for me. I use auxiliarytools_for_xcode_6.1.dmg and ruby 2.1.5p273 with rbenv 0.4.0-129-g7e0e85b on OSX Yosemite 10.10.1.

@atmosx can you check the path of Dictionary Development Kit? It should be `/Volumes/Auxiliary Tools/Dictionary Development Kit`. If not, the correct one can be specified by `-d` option. Please see `rdoc_osx_dictionary --help`.

**Comment by atmosx** [comment]
I re-downloaded Dictionary Dev Kit (Aux tools) and worked fine! Thanks
